# Generated by Django 4.2.3 on 2023-07-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0002_visitorlog_reportmalicious'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urlversion', to='selfurl.shortener')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
