# Generated by Django 4.2.3 on 2023-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0005_remove_visitorlog_country_remove_visitorlog_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='user_agent',
            field=models.BinaryField(),
        ),
    ]
