# Generated by Django 4.2.3 on 2023-07-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0006_alter_visitorlog_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiLogSecretKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField()),
                ('v_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logkey', to='selfurl.visitorlog')),
            ],
        ),
    ]
