# Generated by Django 4.2.3 on 2023-07-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0007_visilogsecretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='shortener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitorlogs', to='selfurl.shortener'),
        ),
    ]
