# Generated by Django 4.2.3 on 2023-07-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0008_alter_visitorlog_shortener'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmalicious',
            name='reasons',
            field=models.TextField(default='', help_text='This report is requested to be done honestly. Because with this report, the target URL will be closed for all those who have taken our service to shorten it for their needs. Your dishonesty may cause us to lose business.', verbose_name='Reasons you are reporting'),
            preserve_default=False,
        ),
    ]
