# Generated by Django 4.2.3 on 2023-07-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0010_reportmalicious_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmalicious',
            name='check_decision',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportmalicious',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
