# Generated by Django 4.2.3 on 2023-07-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0011_reportmalicious_check_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versions',
            name='clicked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
