# Generated by Django 4.2.3 on 2023-07-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='top_banenr',
            field=models.ImageField(blank=True, null=True, upload_to='blog/top_banenr/', verbose_name='Top Banner'),
        ),
    ]
