# Generated by Django 4.2.3 on 2023-07-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_action_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurService',
        ),
    ]
