# Generated by Django 4.2.3 on 2023-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
