# Generated by Django 4.2.3 on 2023-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_reply_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='status',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
