# Generated by Django 4.2.3 on 2023-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_reply_status_contactmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
