# Generated by Django 4.2.3 on 2023-07-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_domain', models.URLField()),
                ('key', models.BooleanField()),
                ('validaty', models.DateTimeField()),
            ],
        ),
    ]
