# Generated by Django 4.2.3 on 2023-07-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licences',
            name='key',
            field=models.BooleanField(help_text='Do not make it true if want to allow the site!'),
        ),
    ]
