# Generated by Django 4.2.3 on 2023-07-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_control', '0003_alter_licences_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licences',
            name='key',
        ),
    ]
