# Generated by Django 4.2.3 on 2023-07-24 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_di1_user_di2_user_di3_user_di4_user_di5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='di9',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
