# Generated by Django 4.2.3 on 2023-07-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_di9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='di1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='di2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='di3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='di4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='di5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='di6',
        ),
        migrations.RemoveField(
            model_name='user',
            name='di7',
        ),
        migrations.RemoveField(
            model_name='user',
            name='di8',
        ),
        migrations.RemoveField(
            model_name='user',
            name='di9',
        ),
    ]
