from . import BASE_DIR, env

DEFAULT_FROM_EMAIL = env("SU_DEFAULT_FROM_EMAIL")
EMAIL_HOST = env("SU_EMAIL_HOST")
EMAIL_PORT= env("SU_EMAIL_PORT")
EMAIL_HOST_USER = env("SU_EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("SU_EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS=False
EMAIL_USE_SSL=True


